### ISSUE TITLE
need a config option to remove the server thats listed automatically

### ISSUE THREAD

**Issue by Xplodin** [lender544/new1.20.1#1]
Left in by mistake?
Idk but id rather not have unrelated servers added to my server.dat

**Comment by PandaLunatique** [comment]
[Fork](https://github.com/PandaLunatique/L_Ender-s-Cataclysm/releases/tag/pp-removed)

**Comment by Xplodin** [comment]
Imagine responding to reddit but cant even take a look here. lol
Adding to the fact this server was added in the latest update with no changelog mentioning  of it

**Comment by Veynam** [comment]
Took me a while to find out which mod did this. Randomly adding an unrelated Pay 2 Win server to the server list without the user knowing is really awful behavior. I really hope this was a mistake on the mod authors side. I'm removing this mod until this issue is officially addressed.

**Comment by Nicodemus111** [comment]
Yeah, this is insane you can't even play purple prison with the mod installed. @lender544 I think you have a responsibility to remove this and never introduce intrusive ads like this again. Stop acting like a corporation that cannot be held responsible and choose some other ad type over this. I think your lack of response to this issue and not listing it in changelogs are very telling. It sure looks like you got bribed by a gambling server and thought your users wouldn't notice. Own up to your mistake and remove the ad.

**Comment by Nicodemus111** [comment]
To be clear it was announced in the changelog and you can turn it off in the config but this is still an insane thing for a mod to do.

**Comment by Veynam** [comment]
@Nicodemus111 I didnt see the announcement but hoenstly dont care regardless, advertising an awful P2W server, intrusive as heck, and even if you delete it, it always re-adds itself to the server list on startup. Just soo lame

**Comment by Nicodemus111** [comment]
Oh I absolutely agree, I just think its important to keep the facts straight when criticizing things.

**Comment by Veynam** [comment]
Agreed, edited my previous posts. Looks like the mod got updated but I can't check if anything related to this matter got changed.

**Comment by Xplodin** [comment]
> To be clear it was announced in the changelog and you can turn it off in the config but this is still an insane thing for a mod to do.

when I updated the mod and checked the CF changelog, there was no mention of the server being added.
either way sorry for being blind to the config

**Comment by Nicodemus111** [comment]
I checked modrinth changelogs so maybe it just was never listed on curseforge.
